# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 08:55
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sosapp', '0002_iexperiencemodel_reportoncemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=25)),
                ('dob', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('p_title', models.CharField(blank=True, max_length=150)),
                ('p_company', models.CharField(blank=True, max_length=150)),
                ('p_city', models.CharField(blank=True, max_length=150)),
                ('p_time_from', models.DateField(blank=True, null=True)),
                ('p_time_to', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
