# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dob',
            new_name='birthdate',
        ),
    ]
