# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0004_auto_20170130_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileModel',
        ),
    ]
