# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 10:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0005_auto_20170130_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=25),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,15}$')]),
        ),
    ]
