# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 11:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0007_auto_20170130_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
