# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-30 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0008_auto_20170130_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
