# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0009_auto_20170130_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='iexperiencemodel',
            name='i_title',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportoncemodel',
            name='r_title',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
