# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0011_auto_20170213_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexperiencemodel',
            name='i_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reportoncemodel',
            name='r_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
