# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-13 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sosapp', '0012_auto_20170213_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iexperiencemodel',
            old_name='i_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='iexperiencemodel',
            old_name='i_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reportoncemodel',
            old_name='r_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='reportoncemodel',
            old_name='r_title',
            new_name='title',
        ),
    ]
